service: taskmanager

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8
  httpApi:
    cors: true
  environment:
    PYTHONPATH: './src'

functions:
  authenticate:
    handler: src/auth/auth.authenticate
    events:
      - httpApi:
          method: GET
          path: /test

plugins:
  - serverless-python-requirements

