service: taskmanager

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8
  httpApi:
    cors: true
  environment:
    PYTHONPATH: '/opt:/opt/python/lib/python3.8/site-packages'
  layers:
    - "${cf:layers-dev.CommonLambdaLayerQualifiedArn}"

functions:
  register:
    handler: user.register.lambda_handler
    events:
      - httpApi:
          method: POST
          path: /register
  
  login:
    handler: user.login.lambda_handler
    events:
      - httpApi:
          method: POST
          path: /login
  
  create_task:
    handler: task.create_task.lambda_handler
    events:
      - httpApi:
          method: POST
          path: /task
  
  update_task:
    handler: task.update_task.lambda_handler
    events:
      - httpApi:
          method: PUT
          path: /task

  get_tasks:
    handler: task.get_tasks.lambda_handler
    events:
      - httpApi:
          method: GET
          path: /task


plugins:
  - serverless-python-requirements