service: taskmanager

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8
  httpApi:
    cors: true
  environment:
    PYTHONPATH: '/opt:/opt/python/lib/python3.8/site-packages'

functions:
  register:
    handler: register.lambda_handler
    layers:
      - "${cf:layers-dev.CommonLambdaLayerQualifiedArn}"
    events:
      - httpApi:
          method: POST
          path: /register

plugins:
  - serverless-python-requirements