service: taskmanager

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8
  httpApi:
    cors: true
  environment:
    PYTHONPATH: '/opt'

functions:
  authenticate:
    handler: auth.authenticate
    layers:
      - "${cf:layers-dev.CommonLambdaLayerQualifiedArn}"
    events:
      - httpApi:
          method: GET
          path: /test

plugins:
  - serverless-python-requirements


